### ISSUE TITLE
Drop down customizer

### ISSUE THREAD

**Issue by justin-peacock** [sixteenbit/gameboy-customizer#1]
Need the following drop downs that will add classes to their respective elements.

**Background**

This changes the background image from light to dark. Light (default) has no class but Dark will add the class `.dark` to the `html`

- Light (selected)
- Dark

**Shell Color**

This changes the background color of the shell. Light Grey (default) has no class but when other options are selected, a class needs to be added to `.shell`. The class is prefixed with .shell-[color-name].

Example:
```html
<div class="shell shell-dark-grey">
```

- Light Grey (selected)
- Black
- White
- Dark Grey
- Yellow
- Red
- Clear
- Clear Green
- Clear Orange
- Clear Blue
- Clear Red

**Button Themes**

This will add predetermined color schemes to all buttons. It will add a class to the container around all buttons which will overwrite any colors. Custom (default) allows for for any colors to be chosen with the X, Y, A, B drop downs.

- Custom (selected)
- Super Famicom
- SNES Purple

I will most likely be adding more soon...

**Button X**

This will add a predetermined color to a specific button. The class will need to be added where the class .button-x is used. The class is prefixed with `.button-[color-name]`.

Example:
```html
<i class="buttons button button-x button-dark-grey"></i>
```

- Burgundy (selected)
- Black
- White
- Light Grey
- Dark Grey
- Purple
- Green
- Blue
- Yellow
- Red
- Turqoise

Repeat for Y, A, B

## To Do

I still need to write styles for Directional and Start/Select but we'll need similar functionality.

**Comment by asaladino** [comment]
Do you want to do this in reactjs, angular, vue, javascript, jquery, etc.?

**Comment by justin-peacock** [comment]
I think it will just be simple jquery. Select an option and it adds the class to the right element. Whatever is easiest.

**Comment by asaladino** [comment]
for the button themes we should do something like this:
```
<div class="buttons burgundy">
	<i class="directional"></i>
	<i class="button button-x"></i>
	<i class="button button-y"></i>
	<i class="button button-a"></i>
	<i class="button button-b"></i>
	<i class="button start-select"></i>
</div>
```

**Comment by justin-peacock** [comment]
the button colors would be specific to each button though. take a look at https://sixteenbit.github.io/gameboy-customizer/custom-example.html

**Comment by asaladino** [comment]
oh, got it. every button can be different.

**Comment by justin-peacock** [comment]
I'm making it where someone could select a pre-determined scheme or pick a custom scheme. The pre-determined ones will be a class on the container like you mentioned and would change colors of all buttons.

See this example https://sixteenbit.github.io/gameboy-customizer/theme-example.html

**Comment by asaladino** [comment]
It looks pretty good and usable. Let me know if you want to make any changes.
